version: "3.9"

services:
  api:
    build: .
    container_name: api
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/app
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=resources_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdb:/var/lib/data

volumes:
  pgdb:
